### ISSUE TITLE
source maps not working in example project?

### ISSUE THREAD

**Issue by marcvk** [joost-de-vries/sbt-typescript#11]
Hi,

I can't get the source maps to work properly in Chrome in my own project. Trying out the example project they don't appear to be working there either. Chrome can't locate the ts files at all and shows the breakpoints in the generated js files.

Kind regards,
Marc van Kempen.

**Comment by joost-de-vries** [comment]
From the top of my head: there's a tsc configuration called `sourceRoot`. That will be used to set the url to the sourcemaps in the js files. Chrome will use that to request the sourcemap from the play server. 
You're right; it would be nice to set that correctly in the activator project. If you find out the correct value pls let me know and I'll update the play-angular2-typescript project. Or you can provide a pull request.

**Comment by joost-de-vries** [comment]
Actually the tsc setting is called `mapRoot`. See [ts handbook](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md)
Since it seems to be an issue of TS knowledge and I haven't heard from you I'm closing this.

**Comment by SlevinBE** [comment]
Hi Joost,

I ran into a similar issue. My project is based on the example project.
I tried setting the mapRoot to "assets", but when I look at the contents of the generated source map file it contains an absolute folder path.

**Comment by joost-de-vries** [comment]
@SlevinBE I'm using the following `tsconfig.json` settings. 

```
    "sourceMap": true,
    "mapRoot": "/assets",
    "sourceRoot": "/assets",
```

If you don't start with a slash it is interpreted as a relative path and tsc prefixes the file location apparently.
This is purely `tsc`. Not `sbt-typescript`.

**Comment by SlevinBE** [comment]
combining the mapRoot and sourceRoot, with a leading "/", like you showed did the trick. Thanks!
