### ISSUE TITLE
Bower support (for angular + polymer)?

### ISSUE THREAD

**Issue by bertvh** [joost-de-vries/sbt-typescript#12]
Just something I want to drop here... I'd like to use a Polymer component inside my angular2 app. The thing is that Polymer is distributed through Bower, while Angular uses npm.

I can install some of the Polymer packages as Bower Webjars, but some of them don't seem to work properly (`You can't use gotoNode for a node which does not represent the same Module as the one represented by this node`) or dependencies aren't resolved.

Any suggestions / experiences / ideas ?

**Comment by joost-de-vries** [comment]
This has nothing to do with `sbt-typescript` as you say yourself. So I'll close this.
