### ISSUE TITLE
Plugin tries to compile dependencies 

### ISSUE THREAD

**Issue by Krever** [joost-de-vries/sbt-typescript#13]
Hi,

I'm trying to modify play-angular2-typescript to use akka-http but I'm stuck on one problem. When i run `stage` task a lot of errors show up from angular sources. 

Have you got any idea what can be wrong? Here are my tsconfig.json, and build.sbt, if it can help. 

```
{
  /* the configuration of the typescript compiler. See docs https://github.com/Microsoft/TypeScript/wiki/Compiler-Options
  The settings outDir and rootDir are managed by sbt-typescript.
  */
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    /* the following two settings are required for angular2 annotations to work*/
    "emitDecoratorMetadata": true,
    "experimentalDecorators":true,
    /* for reading your ts source while debugging from a browser */
    "sourceMap": true,
    "mapRoot": "/assets",
    "sourceRoot": "/assets",
    "rootDirs": ["src/main/assets","src/test/assets"],
    "baseUrl": ".",
    "paths": {
      "*": [
        "*",
        "target/web/node-modules/main/webjars/*"
      ]
    },
    /* noImplicitAny when you want your typescript to be fully typed */
    "noImplicitAny":true,
    "noFallthroughCasesInSwitch":true,
    "noImplicitReturns":true,
    "noImplicitThis":true,
    // "strictNullChecks":true, doesn't work yet with @angular RC4
    "outDir": "./target/ts",
    "lib": ["es6", "dom"]
  },
  /* the information below is not used by sbt-typescript. but you can use it if you want to run tsc -p .*/
  "exclude": [
    "node_modules",
    "project/target",
    "typings/main",
    "typings/main.d.ts",
    "typings/browser",
    "target/web"
  ]
}
```

```
name := """akka-http-angular2-typescript"""
version := "0.1.0-SNAPSHOT"
lazy val root = (project in file(".")).enablePlugins(SbtWeb)

scalaVersion := "2.11.8"
incOptions := incOptions.value.withNameHashing(true)
updateOptions := updateOptions.value.withCachedResolution(cachedResoluton = true)

lazy val akkaVersion = "2.4.6"
/** Note that all webjars dependencies are marked as "provided". This is to avoid them be added to the runtime class path. Just for efficiency. It's not needed.
  * If they weren't marked as provided, they would be added to the runtime class path with the "META-INF/resources/webjars" path prefix. But since the SBT-Web's "webJarsNodeModules" task adds copies of them with the mentioned prefix and module version striped, which is more convenient, we can discard the originals. */
val ngVersion="2.0.0-rc.6"
libraryDependencies ++= Seq(
  // binding logback as the underlying logging framework for SLF4J
  "ch.qos.logback" % "logback-classic" % "1.1.7",

  //akka
  "com.typesafe.akka" %% "akka-actor" % akkaVersion,
  "com.typesafe.akka" %% "akka-stream" % akkaVersion,
  "com.typesafe.akka" %% "akka-http-core" % akkaVersion,
  "com.typesafe.akka" %% "akka-http-experimental" % akkaVersion,
  "com.typesafe.akka" %% "akka-slf4j" % akkaVersion,
  "de.heikoseeberger" %% "akka-http-json4s" % "1.9.0",
  "org.json4s" %% "json4s-native" % "3.4.0",

  //slick
  "com.typesafe.slick" %% "slick" % "3.1.1",
  //"org.slf4j" % "slf4j-nop" % "1.6.4",
  "io.strongtyped" %% "active-slick" % "0.3.4",
  "org.apache.derby" % "derby" % "10.12.1.1",

  //@angular
  "org.webjars.npm" % "angular__common" % ngVersion,
  "org.webjars.npm" % "angular__compiler" % ngVersion,
  "org.webjars.npm" % "angular__core" % ngVersion,
  "org.webjars.npm" % "angular__http" % ngVersion,
  "org.webjars.npm" % "angular__platform-browser-dynamic" % ngVersion,
  "org.webjars.npm" % "angular__platform-browser" % "2.0.0-rc.5",
  "org.webjars.npm" % "angular__router" % "3.0.0-rc.2",
  "org.webjars.npm" % "systemjs" % "0.19.31",
  "org.webjars.npm" % "todomvc-common" % "1.0.2",
  "org.webjars.npm" % "rxjs" % "5.0.0-beta.9",
  "org.webjars.npm" % "es6-promise" % "3.1.2",
  "org.webjars.npm" % "es6-shim" % "0.35.1",
  "org.webjars.npm" % "reflect-metadata" % "0.1.3",
  "org.webjars.npm" % "zone.js" % "0.6.12",
  "org.webjars.npm" % "core-js" % "2.4.0",
  "org.webjars.npm" % "symbol-observable" % "1.0.1",

  "org.webjars.npm" % "typescript" % "2.0.0-dev.20160707",

  //tslint dependency
  "org.webjars.npm" % "tslint-eslint-rules" % "1.2.0",
  "org.webjars.npm" % "codelyzer" % "0.0.25",
  "org.webjars.npm" % "types__jasmine" % "2.2.26-alpha" % "test",

  "org.webjars" % "webjars-locator" % "0.32"

)
dependencyOverrides += "org.webjars.npm" % "minimatch" % "3.0.0"

// the typescript typing information is by convention in the typings directory
// It provides ES6 implementations. This is required when compiling to ES5.
typingsFile := Some(baseDirectory.value / "typings" / "index.d.ts")

// use the webjars npm directory (target/web/node_modules ) for resolution of module imports of @angular/core etc
resolveFromWebjarsNodeModulesDir := true

// use the combined tslint and eslint rules plus ng2 lint rules
(rulesDirectories in tslint) := Some(List(tslintEslintRulesDir.value, ng2LintRulesDir.value))

// If true, sources from the project's base directory are included as main sources.
sourcesInBase := false


// adds, to the runtime classpath, the directories where the webjars are extracted (with META-INF and version stripped).
(managedClasspath in Runtime) ++= WebKeys.nodeModuleDirectories.in(Assets).value
(managedClasspath in Runtime) += WebKeys.webJarsDirectory.in(Assets).value
(managedClasspath in Runtime) += WebKeys.public.in(Assets).value


// run the application in a separate JVM (instead of using the same than SBT)
fork in run := true

enablePlugins(JavaServerAppPackaging)
(managedClasspath in Runtime) += (packageBin in Assets).value
```

And the error from sbt:

> [info] Compiling 24 Scala sources to /home/wpitula/Projects/plandget/target/scala-2.11/classes...
> [info] Typescript linting on 9 source(s)
> [info] Typescript compiling on 9 source(s)
> model contains 62 documentable templates
> [info] Main Scala API documentation successful.
> [info] Packaging /home/wpitula/Projects/plandget/target/scala-2.11/akka-http-angular2-typescript_2.11-0.1.0-SNAPSHOT-javadoc.jar ...
> [info] Done packaging.
> [error] /home/wpitula/Projects/plandget/target/web/node-modules/main/webjars/@angular/platform-browser/core_private.d.ts:7: TS2305 Module '"/home/wpitula/Projects/plandget/target/web/node-modules/main/webjars/@angular/core/index"' has no exported member '**core_private_types**'.
> [error] import { **core_private** as r, **core_private_types** as t } from '@angular/core';
> [error]                                 ^
> [error] /home/wpitula/Projects/plandget/target/web/node-modules/main/webjars/@angular/platform-browser/src/browser.d.ts:0: TS2305 Module '"/home/wpitula/Projects/plandget/target/web/node-modules/main/webjars/@angular/core/index"' has no exported member 'ExceptionHandler'.
> [error] import { ExceptionHandler, PlatformRef } from '@angular/core';
> [error]          ^
> [error] /home/wpitula/Projects/plandget/target/web/node-modules/main/webjars/@angular/platform-browser/src/browser/location/browser_platform_location.d.ts:7: TS2305 Module '"/home/wpitula/Projects/plandget/target/web/node-modules/main/webjars/@angular/common/index"' has no exported member 'UrlChangeListener'.
> [error] import { PlatformLocation, UrlChangeListener } from '@angular/common';
> [error]                            ^
> [error] /home/wpitula/Projects/plandget/target/web/node-modules/main/webjars/@angular/platform-browser/src/security/dom_sanitization_service.d.ts:7: TS2305 Module '"/home/wpitula/Projects/plandget/target/web/node-modules/main/webjars/@angular/core/index"' has no exported member 'SanitizationService'.
> [error] import { SanitizationService, SecurityContext } from '@angular/core';
> [error]          ^
> [error] /home/wpitula/Projects/plandget/target/web/node-modules/main/webjars/@angular/platform-browser/src/web_workers/shared/client_message_broker.d.ts:31: TS2314 Generic type 'Type<T>' requires 1 type argument(s).
> [error]     abstract runOnService(args: UiArguments, returnType: Type): Promise<any>;
> [error]                                                          ^
> [error] 9 errors found
> [error](web-assets:typescript) com.typesafe.sbt.web.CompileProblemsException
> [error] Total time: 5 s, completed Sep 2, 2016 8:42:45 AM

**Comment by joost-de-vries** [comment]
I I understand correctly this is not an issue with `sbt-typescript` right?

**Comment by Krever** [comment]
I can't tell, because I'm not an expert on tsc, so I cannot say if something is missconfigured on my side or something is wrong with sbt-typescript. But sbt-typescript tries to compile files from target directory and this is probably not desirable behaviour.

**Comment by joost-de-vries** [comment]
`sbt-typescript` uses `sbt-web`. So if your web framework supports `sbt-web` it should work.
Akka Http doesn't support `sbt-web` so I'm afraid I can't help you there.
[This project](https://github.com/readren/akkaHttp-angular2-typescript) aims to support Akka Http. And I think you're using their code. Maybe they can help you?
