### ISSUE TITLE
Is there any plan to upgrade to sbt 1.0?

### ISSUE THREAD

**Issue by WayneWang12** [joost-de-vries/sbt-typescript#23]
sbt 1.0.1 is released. I'm wondering if there is any plan for upgrade to sbt 1.0? Seems that 1.0 will accelerate the speed of resolving dependencies.

**Comment by joost-de-vries** [comment]
Yep, definitely. I was waiting for `sbt-web` and `sbt-js-engine` to be upgraded to sbt 1.0. 
That has happened a week ago. And now I'll have to find the time to setup a cross build. 

I guess this becomes more urgent once Play has gone to supporting sbt 1.0

Tx for the issue. This tells me that `sbt-typescript` is being used and that the porting would be useful.

As far as the speed goes: I've discussed this with James Ward. I think it has something to do with how npm defines ranges as dependencies.

**Comment by WayneWang12** [comment]
Thank you @joost-de-vries ! Of course your plugins are useful! Glad to hear that you have the plan.

I'll keep using it because my stack is on Play framework. And play-angular-seed helps me a lot. I believe there are many people who also loves angular and Play framework. I'll recommend your work to them. 

Thanks for your work and open-souring it. Really appreciate it.

**Comment by joost-de-vries** [comment]
I've upgraded the plugin `2.5.2-1`: the last version is available for sbt 0.13.x and 1.0.x. Let me know if it works for you.

**Comment by WayneWang12** [comment]
Thank you @joost-de-vries ! I'll update my plugin now. :smile:

**Comment by joost-de-vries** [comment]
Let me know how it goes. 
Personally I can't switch to 1.0 yet because my sass plugin hasn't been ported yet. :-)

**Comment by WayneWang12** [comment]
I'm using your play-angular-typescript. Outside the project I don't know how to use it because I'm just new to front-end programming... Refreshing will fail if I change sbt version to 1.0.0 because of the missing of Play framework plugin and all other plugins. I'm not so hurry to upgrade to 1.0 because what inconvient me is that resolving webjars dependencies is so slow in my country. But except for slowness, it works well. However, the new feature in sbt 1.0.0 can accelerate resolving. So I come to ask if you have plan for 1.0. I'm also waiting for play framework to update. 

Seems it's coming.

**Comment by joost-de-vries** [comment]
I've updated the demo project to the play version that supports sbt 1.0. So I'll close this.

**Comment by WayneWang12** [comment]
Thank you! I just noticed that play have release 2.6.6. Thanks for your quick response. Your are really awesome!

**Comment by joost-de-vries** [comment]
Ha! Tx for your update.
Yeah, I was eager to see whether there's any speed improvement in resolving webjars with sbt 1.0
So I ported the angular demo project immediately. 
What are your experiences? Are webjars faster with sbt 1.0 / Play 2.6.6?

**Comment by WayneWang12** [comment]
Definitely quickier. In China, although there are still reasons which slow down our speed in Internet that I can't control, the speed of downloading dependencies getting really faster than before which you may not experience in your country. Really thanks for your work, it saves me a lot of time, haha
