### ISSUE TITLE
Intellij does not resolve angular2 (or other) webjar libs

### ISSUE THREAD

**Issue by kadriaen** [joost-de-vries/sbt-typescript#3]
Hi,

We're currently struggling keeping our gulp based angular2 project sane, so I very much appreciate how your webjar approach simplifies things.

I do seem to have trouble telling my IDE where to find the angular2 webjar files for autocompletion etc., is it possible to configure this in any way?

I realize this is not an issue against the sbt-typescript project, but I'm wondering if there's a solution to this. 

Many thanks!

**Comment by kadriaen** [comment]
It is possible to make Intellij find the webjars for autocompletion and navigation by forcing it not to ignore the web-modules directory in the target folder, but this is not what you want.

Seems to be an Intellij bug that it does not use the webjar libraries downloaded by sbt, even though they are present in the project configuration.

**Comment by joost-de-vries** [comment]
I've added a `setupTscCompilation` task. At this point that copies the npm webjars to the `node_modules` directory. As soon as TS 1.9 becomes stable we'll be able to use the webjars without copying them.

**Comment by kadriaen** [comment]
Works great, thanks!

**Comment by joost-de-vries** [comment]
Dat is goed om te horen!
