### ISSUE TITLE
Failed compilation with dependencies containing typescript files

### ISSUE THREAD

**Issue by Alcalion** [joost-de-vries/sbt-typescript#8]
Hello!

I am currently working on a project where we have injected your plugin to compile our typescript files.
Everything was working fine until I had to use a dependency (angular2-jwt, angular2-material or any dependency with some ts files) which contains typescript files. The problem is that those files are getting compiled even though they are not included in rootDir and included in the excluded folders.

When compiling we get the following mistake :  
`TS6059 File 'path/to/file' is not under 'rootDir' 'rootDir/path'. 'rootDir' is expected to contain all source files.`
As a consequence, my ts files are not compiled and they appear as empty folders (with a js extension though). The rootDir compiler option is definitely the key to it but I can't seem to find any solution after a long week of research and tries. Is there already a workaround the fact that rootDir is an ignored compiler option? If not is it a work in progress or can I do anything about it?

About our project, we are using the Play 2.5.4, Scala 2.11.8 and are using the latest versions available on webjars for angular2 (basically the webjars you are using in play-angular2-typescript).

If you consider that this is not an issue on your side, can you contact me at dev@lespetitsentrepreneurs.com ?
And thanks already for your plugins they are truly helpful.

**Comment by joost-de-vries** [comment]
Compiles just fine for me.
Try upgrading to the most recent version of sbt-typescript.
