### ISSUE TITLE
Wrong unpacked folder name of webjars (rxjs)

### ISSUE THREAD

**Issue by awilhelmer** [joost-de-vries/sbt-typescript#9]
Hello,

i dont know where to address this issue. It can be a problem in webjar or in sbt-web as well. In my project with angular2 and your typescript compiler plugin (great work btw.!) the webjar of RxJs is unpacked in a wrong folder name in the target output folder (see picture). The Typescript Compiler and my IDE throw errors if i try to import Rxjs classes like Observable. I looked into the webjar but didnt see any problems with it. I dont know why this folder name is created. "Ben Lesh" is only in the package.json file specially in the author and contributor tag.

![image](https://cloud.githubusercontent.com/assets/1927516/17212788/83034116-54d1-11e6-8939-2a281a8fa9f2.png)

**Comment by joost-de-vries** [comment]
I saw this as well a while ago. I seem to recall that it's an issue with the webjar of a specific Rx version. The Rx team made a faulty release and made a good release later with the same version nr. Unfortunately in the mean time a webjar was made of the faulty version.
Either you can register an issue with github/webjar/webjar and see if they can help you remove the faulty webjar so that you can create a new webjar for that Rx version. Or you can change to a different Rx version.

**Comment by awilhelmer** [comment]
Thanks for your hint. I used 5.0.0-beta.10 (newest one), with 5.0.0-beta.9 the problem disappears.

**Comment by joost-de-vries** [comment]
Hm. I've seen this problem with an old version of Rx. But so it's a problem again with the newest Rx version!
I've imported beta.10 again into webjars.org. But I'm not sure that the original webjar version gets replaced that way.
Do you still see the same problem with beta.10?

**Comment by joost-de-vries** [comment]
This turns out to be [an issue](https://github.com/webjars/webjars-locator-core/issues/14) with a dependency: `webjars-locator-core`. This has been solved in `beta.4`.

**Comment by awilhelmer** [comment]
On 5.0.0-beta.12 i get a NullpointerException:

`java.lang.NullPointerException: 
     org.webjars.WebJarExtractor.getJsonNodeModuleId(WebJarExtractor.java:341)
     org.webjars.WebJarExtractor.findWebJarsInJarFile(WebJarExtractor.java:286)
     org.webjars.WebJarExtractor.extractWebJarsTo(WebJarExtractor.java:113)
     org.webjars.WebJarExtractor.extractAllNodeModulesTo(WebJarExtractor.java:83)
     com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$generateNodeWebJars$1.apply(SbtWeb.scala:427)
     com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$generateNodeWebJars$1.apply(SbtWeb.scala:426)
     com.typesafe.sbt.web.SbtWeb$.withWebJarExtractor(SbtWeb.scala:419)
     com.typesafe.sbt.web.SbtWeb$.com$typesafe$sbt$web$SbtWeb$$generateNodeWebJars(SbtWeb.scala:425)
     com.typesafe.sbt.web.SbtWeb$$anonfun$39.apply(SbtWeb.scala:300)
     com.typesafe.sbt.web.SbtWeb$$anonfun$39.apply(SbtWeb.scala:300)
     scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
     sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
     sbt.std.Transform$$anon$4.work(System.scala:63)
     sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
     sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
     sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
     sbt.Execute.work(Execute.scala:237)
     sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
     sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
     sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
     sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
     java.util.concurrent.FutureTask.run(Unknown Source)
     java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
     java.util.concurrent.FutureTask.run(Unknown Source)
     java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
     java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
     java.lang.Thread.run(Unknown Source)`

**Comment by joost-de-vries** [comment]
Yes, I encountered this as well last week. It seems to be a problem in `webjars-locator-core`.
Tx for registering. 
 I've updated the [issue](https://github.com/webjars/webjars-locator-core/issues/14).
Hopefully James knows what's going on.

**Comment by awilhelmer** [comment]
It's really interesting that RxJs makes many problems with webjars. But i think RxJs simply deploys wrong packages to NPM and overwrite fixes. Maven doesn't support this behavior.

**Comment by joost-de-vries** [comment]
James has fixed the issue and I published a version of sbt-typescript that uses this. It's beta.5. Let me know if it works for you as well.

**Comment by awilhelmer** [comment]
Works for me. And RxJs is the reason why the app is loading ~500 HTTP requests on initial startup. Minifieing isn't working, because:
https://github.com/angular/angular/issues/9359

**Comment by joost-de-vries** [comment]
Great that it works. So I can close the issue.

Yeah, I recognise the issue with lots of Rx files. I'm tracking the same issue.
